#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - "12.13.0"

before_script:
  - npm i

#运行的脚本命令
script:
    - npm run lint
    - npm run test
  
after_success:
    - npm run nyc:cov

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    - /^greenkeeper/.*$/
